<script setup>
/**
 * @file MetadataSidebar.vue
 * @description A comprehensive sidebar component for viewing and interacting with image-specific technical metadata.
 *
 * This component provides a detailed breakdown of the generation parameters embedded within
 * AI-generated images. It displays prompts, negative prompts, model information, and
 * technical settings (CFG, Steps, Seed) in a structured, readable format. It also
 * facilitates user interaction through star ratings, clipboard copying, and AI tag discovery.
 *
 * Key functionalities:
 * - **Metadata Visualization:** Renders technical parameters in a clean grid, with
 *   specialized handling for long text blocks like prompts.
 * - **Interactive Rating:** Implements a 5-star rating system that persists changes
 *   directly to the backend.
 * - **Clipboard Integration:** Provides quick-copy buttons for prompts and raw JSON metadata.
 * - **AI Tag Discovery:** Displays tags generated by the WD14 model and allows users
 *   to initiate a global search for any specific tag with a single click.
 * - **System Integration:** Offers direct access to the physical file location via
 *   the OS file explorer.
 * - **Raw Data Inspection:** Includes a modal dialog for viewing the complete,
 *   unprocessed metadata string or JSON workflow.
 * - **Custom Metadata Editing:** Allows users to override prompts, models, and add personal notes.
 */
import {useBrowserStore} from '@/stores/browser';
import {computed, ref, watch} from 'vue';
import api from '@/services/api';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Chip from 'primevue/chip';
import Divider from 'primevue/divider';
import Dialog from 'primevue/dialog';
import LButton from '@/components/ds/LButton.vue';
import { Copy, X } from 'lucide-vue-next';
import {useToast} from 'primevue/usetoast';


const store = useBrowserStore();
const toast = useToast();
const meta = computed(() => store.currentMetadata);
const isRawVisible = ref(false);
const isEditing = ref(false);

const editForm = ref({
  userNotes: '',
  customPrompt: '',
  customNegativePrompt: '',
  customModel: ''
});

watch([isEditing, meta], ([editing, newMeta]) => {
  if (editing) {
    editForm.value = {
      userNotes: newMeta.user_notes || '',
      customPrompt: newMeta.custom_prompt || newMeta.Prompt || '',
      customNegativePrompt: newMeta.custom_negative_prompt || newMeta.Negative || '',
      customModel: newMeta.custom_model || newMeta.Model || ''
    };
  }
});

const fileName = computed(() => {
  if (!store.selectedFile) return 'No Selection';
  return store.selectedFile.split(/[\\/]/).pop();
});

const copyToClipboard = (text) => {
  navigator.clipboard.writeText(text);
  toast.add({severity: 'info', summary: 'Copied', detail: 'Text copied to clipboard', life: 1500});
};

const loras = computed(() => {
  if (meta.value.Loras) return meta.value.Loras.split(',').map(s => s.trim());
  return [];
});

const formatLoraName = (loraStr) => {
  if (!loraStr) return '';
  let cleaned = loraStr.trim();
  if (cleaned.startsWith('<lora:') && cleaned.endsWith('>')) {
    return cleaned;
  }
  const parts = cleaned.split(':');
  if (parts.length >= 2) {
    return `<lora:${parts[0].trim()}:${parts[1].trim()}>`;
  }
  return `<lora:${cleaned}>`;
};


const getLoraCleanName = (loraStr) => {
  if (!loraStr) return '';
  let cleaned = loraStr.trim();
  if (cleaned.startsWith('<lora:') && cleaned.endsWith('>')) {
    cleaned = cleaned.substring(6, cleaned.length - 1);
  }
  const parts = cleaned.split(':');
  return parts[0].trim();
};

const copyLoraName = (loraStr) => {
  const fullTag = formatLoraName(loraStr);
  if (!fullTag) return;
  navigator.clipboard.writeText(fullTag);
  toast.add({ severity: 'info', summary: 'Copied', detail: `Copied "${fullTag}" to clipboard`, life: 1500 });
};




const openFileLocation = async () => {
  if (!store.selectedFile) return;
  try {
    await api.post('/system/show-in-explorer', null, {params: {path: store.selectedFile}});
  } catch (e) {
  }
};

const formattedRawMeta = computed(() => {
  if (!meta.value.Raw) return 'No raw data available.';
  try {
    const parsed = JSON.parse(meta.value.Raw);
    return JSON.stringify(parsed, null, 2);
  } catch (e) {
    return meta.value.Raw;
  }
});

const resetRating = () => {
  store.setRating(0);
};

const setRating = (rating, event) => {
  store.setRating(rating);
  if (event && event.target) {
    const button = event.target.closest('button');
    if (button) {
      button.blur();
    } else {
      event.target.blur();
    }
  }
};

const openTagger = () => {
  store.setTaggerOpen(true);
};

const saveMetadata = async () => {
  try {
    await store.updateMetadata(editForm.value);
    isEditing.value = false;
    toast.add({severity: 'success', summary: 'Saved', detail: 'Metadata updated successfully', life: 2000});
  } catch (e) {
    toast.add({severity: 'error', summary: 'Error', detail: 'Failed to save metadata', life: 3000});
  }
};

const cancelEdit = () => {
  isEditing.value = false;
};

</script>

<template>
  <div class="metadata-sidebar-glass h-full flex flex-column" style="width: 380px; min-width: 380px;">
    <div class="p-3 border-bottom-1 border-white-alpha-10" style="background: rgba(255,255,255,0.02)">
      <div class="font-bold text-base mb-2 text-overflow-ellipsis overflow-hidden white-space-nowrap text-gradient"
           :title="fileName">
        {{ fileName }}
      </div>
      <div class="flex gap-2 justify-content-between">
        <div class="flex gap-2">
          <Button icon="pi pi-folder-open" class="p-button-sm p-button-text text-white"
                  v-tooltip.bottom="'Open File Location'" @click="openFileLocation"/>
          <Button icon="pi pi-code" class="p-button-sm p-button-text text-white" v-tooltip.bottom="'View Raw Metadata'"
                  @click="isRawVisible = true"/>
          <Button icon="pi pi-tags" class="p-button-sm p-button-text text-white" v-tooltip.bottom="'Tag Image with WD14'"
                  @click="openTagger"/>
        </div>
        <div>
          <Button v-if="!isEditing" icon="pi pi-pencil" class="p-button-sm p-button-text text-white"
                  v-tooltip.bottom="'Edit Metadata / Add Notes'" @click="isEditing = true"/>
          <div v-else class="flex gap-1">
            <Button icon="pi pi-check" class="p-button-sm p-button-success p-button-text"
                    v-tooltip.bottom="'Save Changes'" @click="saveMetadata"/>
            <Button icon="pi pi-times" class="p-button-sm p-button-danger p-button-text"
                    v-tooltip.bottom="'Cancel'" @click="cancelEdit"/>
          </div>
        </div>
      </div>
    </div>

    <div class="flex-grow-1 overflow-y-auto p-3 custom-scrollbar">
      <div class="flex flex-column align-items-center mb-3">
        <div class="flex justify-content-center gap-1">
          <Button v-for="i in 5" :key="i"
                  :icon="i <= store.currentRating ? 'pi pi-star-fill' : 'pi pi-star'"
                  class="p-button-text p-button-warning p-0 w-2rem h-2rem star-btn"
                  :class="{ 'text-yellow-500': i <= store.currentRating }"
                  @click="(e) => setRating(i, e)"/>
        </div>
        <span class="text-xs text-500 cursor-pointer hover:text-white mt-1" @click="resetRating">Reset</span>
      </div>

      <div class="text-gradient font-bold text-xl mb-3 text-center">Metadata</div>

      <Divider class="border-white-alpha-10"/>

      <div v-if="!isEditing">
        <div class="mb-3">
          <div class="flex justify-content-between align-items-center mb-1">
            <span class="font-bold text-sm text-500">PROMPT</span>
            <Button icon="pi pi-copy" class="p-button-text p-button-sm p-0 w-2rem h-2rem text-500"
                    v-tooltip.left="'Copy Prompt'" @click="copyToClipboard(meta.custom_prompt || meta.Prompt)"/>
          </div>
          <div class="glass-box p-2 border-round text-sm line-height-3 select-text"
               style="max-height: 150px; overflow-y: auto;">
            {{ meta.custom_prompt || meta.Prompt || 'No prompt found' }}
            <span v-if="meta.custom_prompt" class="text-xs text-yellow-500 block mt-1">(Custom Override)</span>
          </div>
        </div>

        <div class="mb-3">
          <div class="flex justify-content-between align-items-center mb-1">
            <span class="font-bold text-sm text-red-400">NEGATIVE PROMPT</span>
            <Button icon="pi pi-copy" class="p-button-text p-button-sm p-0 w-2rem h-2rem text-500"
                    v-tooltip.left="'Copy Negative Prompt'" @click="copyToClipboard(meta.custom_negative_prompt || meta.Negative)"/>
          </div>
          <div class="glass-box p-2 border-round text-sm line-height-3 select-text"
               style="max-height: 100px; overflow-y: auto;">
            {{ meta.custom_negative_prompt || meta.Negative || 'No negative prompt' }}
            <span v-if="meta.custom_negative_prompt" class="text-xs text-yellow-500 block mt-1">(Custom Override)</span>
          </div>
        </div>

        <div class="mb-3" v-if="meta.user_notes">
          <span class="font-bold text-sm text-blue-400 block mb-1">NOTES</span>
          <div class="glass-box p-2 border-round text-sm line-height-3 select-text white-space-pre-wrap">
            {{ meta.user_notes }}
          </div>
        </div>

        <Divider class="border-white-alpha-10"/>

        <div class="grid grid-nogutter gap-3">
          <div class="col-11">
            <label class="block text-xs text-500 mb-1">Model</label>
            <InputText :value="meta.custom_model || meta.Model || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>
          <div class="col-5">
            <label class="block text-xs text-500 mb-1">Sampler</label>
            <InputText :value="meta.Sampler || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>
          <div class="col-5">
            <label class="block text-xs text-500 mb-1">Scheduler</label>
            <InputText :value="meta.Scheduler || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>
          <div class="col-11">
            <label class="block text-xs text-500 mb-1">Seed</label>
            <InputText :value="meta.Seed || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>

          <div class="col-5">
            <label class="block text-xs text-500 mb-1">CFG</label>
            <InputText :value="meta.CFG || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>
          <div class="col-5">
            <label class="block text-xs text-500 mb-1">Steps</label>
            <InputText :value="meta.Steps || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>
          <div class="col-5">
            <label class="block text-xs text-500 mb-1">Resolution</label>
            <InputText :value="meta.Resolution || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>
          <div class="col-5">
            <label class="block text-xs text-500 mb-1">Size</label>
            <InputText :value="meta.FileSize || '-'" readonly class="w-full p-inputtext-sm glass-input"/>
          </div>
        </div>

        <Divider class="border-white-alpha-10"/>

        <div class="mb-3">
          <span class="block font-bold text-sm text-500 mb-2">LoRAs</span>
          <div class="flex flex-wrap gap-2">
            <span
              v-for="lora in loras"
              :key="lora"
              class="lora-chip text-xs cursor-pointer"
              title="Click to copy LoRA name"
              @click="copyLoraName(lora)"
            >
              {{ formatLoraName(lora) }}
            </span>


            <span v-if="loras.length === 0" class="text-500 text-sm italic">None</span>
          </div>
        </div>

        <div class="mb-3" v-if="meta.ai_tags">
          <div class="text-gray-400 text-sm mt-4 mb-2 font-bold">Detected AI Tags (WD14)</div>
          <div class="flex flex-wrap gap-2">
            <Chip v-for="tag in meta.ai_tags.split(', ')" :key="tag" :label="tag"
                  class="ai-tag-chip text-xs cursor-pointer"
                  @click="store.search(tag)"/>
          </div>
        </div>
      </div>

      <div v-else class="flex flex-column gap-3">
        <div>
          <label class="block text-xs font-bold text-blue-400 mb-2">User Notes</label>
          <Textarea v-model="editForm.userNotes" rows="4" class="w-full glass-input" placeholder="Add your personal notes here..."/>
        </div>

        <div>
          <label class="block text-xs font-bold text-500 mb-2">Custom Prompt Override</label>
          <Textarea v-model="editForm.customPrompt" rows="6" class="w-full glass-input" placeholder="Override the extracted prompt..."/>
        </div>

        <div>
          <label class="block text-xs font-bold text-red-400 mb-2">Custom Negative Prompt Override</label>
          <Textarea v-model="editForm.customNegativePrompt" rows="4" class="w-full glass-input" placeholder="Override the extracted negative prompt..."/>
        </div>

        <div>
          <label class="block text-xs font-bold text-500 mb-2">Custom Model Override</label>
          <InputText v-model="editForm.customModel" class="w-full glass-input" placeholder="Override model name..."/>
        </div>
      </div>
    </div>

    <Dialog v-model:visible="isRawVisible" modal header="Raw Metadata" style="width: 640px;">
      <pre class="raw-meta-pre">{{ formattedRawMeta }}</pre>
      <template #footer>
        <div class="flex justify-content-end gap-2 pt-2">
          <LButton variant="secondary" size="sm" @click="copyToClipboard(formattedRawMeta)">
            <template #icon><Copy :size="14" /></template>
            Copy Text
          </LButton>
          <LButton variant="primary" size="sm" @click="isRawVisible = false">
            <template #icon><X :size="14" /></template>
            Close
          </LButton>
        </div>
      </template>
    </Dialog>

  </div>
</template>

<style scoped>
.metadata-sidebar-glass {
  background: var(--color-surface-1, #14151B);
  border-left: 1px solid var(--color-border-subtle, rgba(255, 255, 255, 0.06));
  box-shadow: var(--shadow-panel, 0 20px 60px -20px rgba(0,0,0,0.65));
}

.glass-input {
  background: var(--color-surface-2, #23252F) !important;
  border: 1px solid var(--color-border-default, rgba(255, 255, 255, 0.10)) !important;
  color: var(--color-text-primary, #F2F3F7) !important;
  border-radius: var(--radius-sm, 6px) !important;
}

.glass-box {
  background: var(--color-surface-2, #23252F);
  border: 1px solid var(--color-border-subtle, rgba(255, 255, 255, 0.06));
  border-radius: var(--radius-md, 8px);
}

.lora-chip {
  display: inline-flex;
  align-items: center;
  background: var(--color-surface-2, #23252F) !important;
  color: var(--color-accent-secondary, #9B7EF5) !important;
  border: 1px solid var(--color-border-subtle, rgba(255, 255, 255, 0.08)) !important;
  border-radius: var(--radius-sm, 6px) !important;
  font-family: var(--font-mono, "JetBrains Mono", monospace) !important;
  font-size: 11px !important;
  padding: 4px 10px !important;
  word-break: break-all;
  transition: all var(--duration-fast, 120ms) var(--ease-standard);
}

.lora-chip:hover {
  background: rgba(155, 126, 245, 0.12) !important;
  border-color: rgba(155, 126, 245, 0.35) !important;
}


:deep(.ai-tag-chip.p-chip),
.ai-tag-chip {
  background: var(--color-accent-primary-bg, rgba(79, 216, 208, 0.12)) !important;
  color: var(--color-accent-primary, #4FD8D0) !important;
  border: 1px solid rgba(79, 216, 208, 0.25) !important;
  border-radius: 999px !important;
}

:deep(.ai-tag-chip.p-chip:hover),
.ai-tag-chip:hover {
  background: rgba(79, 216, 208, 0.22) !important;
}


.text-yellow-500 {
  color: var(--color-warning, #F5B84E) !important;
}

.text-red-400 {
  color: var(--color-danger, #F2665B) !important;
}

.text-blue-400 {
  color: var(--color-accent-primary, #4FD8D0) !important;
}

.text-500 {
  color: var(--color-text-secondary, #9294A3) !important;
}

.text-white {
  color: var(--color-text-primary, #F2F3F7) !important;
}

.border-white-alpha-10 {
  border-color: var(--color-border-subtle, rgba(255, 255, 255, 0.06)) !important;
}

.star-btn:focus {
  box-shadow: none !important;
  outline: none !important;
}

.raw-meta-pre {
  background: var(--color-surface-2, #23252F);
  border: 1px solid var(--color-border-subtle, rgba(255, 255, 255, 0.06));
  border-radius: var(--radius-md, 8px);
  padding: 16px;
  color: var(--color-text-primary, #F2F3F7);
  font-family: var(--font-mono, "JetBrains Mono", monospace);
  font-size: 12px;
  line-height: 1.5;
  max-height: 60vh;
  overflow-y: auto;
  white-space: pre-wrap;
  word-break: break-word;
  margin: 0;
}
</style>


